### ISSUE TITLE
suggestion - disable "Skip Navigation" element

### ISSUE THREAD

**Issue by AliasSquizzie** [Syndamia/min-youtube-element-blocker#2]
I've tested a modified version which makes pages suitable for printing by removing the otherwise intrusive 'skip navigation' button. Have included note in code that this button is an accessibility feature in case that matters to user.

suggested additions: 
```
// ==/UserScript==
...
  // Skip navigation button is an accessibility feature but can get in the way of printing    
  "hideSkipNavButton": true,
};
...

/* CSS that is added to page for hiding the elements */
...

     "hideSkipNavButton": `
    #skip-navigation.ytd-masthead {
      display: none !important;
    }`,
...

```

**Comment by Syndamia** [comment]
Sorry for the late response, I hadn't checked my notifications in a while.
I think this is a pretty cool addition, if you can/want, feel free to make it a pull request. This way you would, at the very least, get more easily credit for your idea and work figuring it out.
Otherwise I can add it no problem.

**Comment by AliasSquizzie** [comment]
No worries re: delay - by my standards your reply was practically immediate!

Thanks for this suggestion, I appreciate the option. I've not done a pull request before but taken a look and think I've set one up properly - fingers crossed it both came through to you and still works ok!

thanks again and great work on the original - I wouldn't have been able to make my addition had yours not been so clearly described.
